runtime: python39

entrypoint: gunicorn -b :$PORT app:app

# Optional: If you want to deploy this as the default service
# in your project (so it appears at https://<PROJECT_ID>.appspot.com),
# you can add:
# service: default
